# ✅ Name of the Workflow
name: Pipeline CI/CD Backend-api

# ✅ Required Permissions to upload SARIF results to GitHub Security tab
permissions:
  contents: read
  security-events: write  # Required for uploading SARIF to GitHub code scanning

# ✅ Trigger this workflow on push to main branch
on:
  push:
    branches:
      - main

# ✅ Environment variables to be used in the pipeline
env:
  BUILD_NUMBER: ${{ github.run_number }}  # Unique build number for the pipeline run
  IMAGE_NAME: backend-api  # Name of the Docker image
  BACKEND_URL: "https://api.lebondeveloppeur.net"  # URL for the backend to check its health

jobs:

  # ✅ Unit Tests Job
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  # ✅ Secret Scanning Job using Gitleaks
  secret-scan-job:
    runs-on: ubuntu-latest
    needs: unit-test-job  # Run after unit tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  # ✅ Static Code Analysis Job (SonarQube)
  sonarqube-code-quality-scan-job:
    runs-on: ubuntu-latest
    needs: secret-scan-job
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # ✅ Vulnerability Scanning Job (Snyk)
  snyk-code-security-scan-job:
    runs-on: ubuntu-latest
    needs: sonarqube-code-quality-scan-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependency Scanning Tool (Snyk)
        run: npm install -g snyk

      - name: Snyk Authentication
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Vulnerability Scan
        run: snyk test

  # ✅ Docker Image Scanning Job (Trivy)
  trivy-image-security-scan-job:
    runs-on: ubuntu-latest
    needs: snyk-code-security-scan-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download and install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.tar.gz -o trivy.tar.gz
          tar xzvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Run Trivy Docker image vulnerability scan
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          trivy image ${{ env.IMAGE_NAME }}

  # ✅ Build and Push Docker Image Job
  build-and-push-job:
    runs-on: ubuntu-latest
    needs: trivy-image-security-scan-job
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image with specific version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

      - name: Push Docker image with specific version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

      - name: Tag Docker image with latest version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image with latest version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  # ✅ Deploy to VPS Job
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-and-push-job
    steps:
      - name: Connect to the VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/ubuntu/devops-scripts/api
            sudo git pull
            sudo docker compose pull
            sudo docker compose up -d --force-recreate --remove-orphans
            sudo docker image prune -af

  # ✅ Health Check Job
  health-check-job:
    runs-on: ubuntu-latest
    needs: deploy-job
    steps:
      - name: Health Check - Verify Backend Availability
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.BACKEND_URL }}/health)
          echo "Received response code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with response code $response"
            exit 1
          else
            echo "Health check passed successfully!"
          fi

      - name: Notify Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "✅ *Pipeline CI/CD Backend-api terminé avec succès !*\n🔁 Branche: `${{ github.ref_name }}`\n🏗 Build: `${{ env.BUILD_NUMBER }}`\n🔗 [Voir le workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "❌ *Échec du pipeline CI/CD Backend-api* ❗️\n🔁 Branche: `${{ github.ref_name }}`\n🔗 [Voir les logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
