name : Pipeline CI/CD backend-api

on :
    push :
        branches :
            [main,master,dev]


jobs:
  #unit test 
  Test_Unitaire:
    runs-on: ubuntu-latest 
    steps:
      - name: clone code 
        uses: actions/checkout@v5

      - name: install dependencies
        run: npm install

      - name: run unit tests
        run: npm run test
        
  #build and push image 
  #build image 
  #docker login 
  #docker push 
  build-and-push:
    runs-on: ubuntu-latest
