name : Pipeline CI/CD backend-api

on :
    push :
        branches :
            [main,master,dev]


jobs:
  #unit test 
  Test_Unitaire:
    runs-on: ubuntu-latest 
    steps:
      - name: clone code 
        uses: actions/checkout@v5

      - name: install dependencies
        run: npm install

      - name: run unit tests
        run: npm run test
  
  #checkout code | clone car chaque job est separer et dans un runners specifique       
  #build and push image 
  #build image 
  #docker login 
  #docker push 
  build-and-push:
    runs-on: ubuntu-latest
    needs: Test_Unitaire
    steps: 
        - name: clone code 
          uses: actions/checkout@v5
        - name: build docker image
          run: docker build -t adeem07/backend-api-session14 .

        # docker tag image
        - name: tag image 
          run: docker tag adeem07/backend-api-session14 adeem07/backend-api-session14:${{ github.run_number }}
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: list image 
          run: docker images  
          
        - name: push docker image
          run: docker push adeem07/backend-api-session14:${{ github.run_number }}


  #deploy to vps